name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: echo computer version
        run: cat /etc/os-release
      - name: python cmd
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    needs: ["run-shell-command"]
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location

      - name: Directory Bash
        run: pwd
        shell: bash
